### ISSUE TITLE
Fix peep loading positions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/objects#13]
This bit of code is not handling the peep loading positions correctly for rides with 16bit loading positions.

https://github.com/OpenRCT2/objects/blob/master/tools/objexport/PropertyExtractor.fs#L430-L440

Loading positions counts come in two different forms. 8 bit and 16 bit.
First you read the 8bit count.
If the 8 bit count is 255 then you load the 16 bit count.

Loading positions are then split into 3 different types: offsets, waypoints_1, waypoints_2.

Offsets are an array of `sint8` of size count.

Waypoints_1/2 have an initial byte that indicates if it is type 1 (if its 0) or type 2 (anything else).
After this there is an array of 3 waypoints comprising of x, y coordinates as sint8's.
There is then a blank waypoint (16 bits).
The above is then repeated for `(count - 1) / (2 * 4)`.

**Comment by IntelOrca** [comment]
The count variable is already read by the object data library:
https://github.com/trigger-death/RCT2ObjectData/blob/master/RCT2ObjectData/Objects/Types/Attraction.cs#L161

This is just spitting out the raw byte arrays, so I think the issue is in OpenRCT2 rather than this.

**Comment by duncanspumpkin** [comment]
Oh okay. Cam we fix it in json objects so the way point data is in arrays of two coordinates

**Comment by IntelOrca** [comment]
@duncanspumpkin we can, do you think we should do that now or later?

Could you type some examples of what the new json would look like for the different formats?

**Comment by duncanspumpkin** [comment]
Okay,
Will do that at lunch. Some more notes to myself.

Waypoints type 1 are for rides where peeps all enter the ride at the same point such as in crooked houses (check to make sure crooked houses are waypointed). Type 2 waypoints the peeps seating position is split into four+ segments (enterprise, Twister). Number of waypoints sets (3 xy coords) should be number of seats x 4 (entrance directions) x 4 (track directions). Enterprise is special and has double?? 8 segments?? Type 1 are special and have half the track directions?? Do some rides only have two orientations??

**Comment by duncanspumpkin** [comment]
Offsets do not require any changes to json format can stick to:
```
"loadingPositions": [
            [1, 2],
            [3, 4]
        ]
```
They should really be linked to the car structure and not a separate entry. That would match how they are used. We should perhaps have a check to make sure that `numSeats & 0x7F` is equal to the length of each array.

For waypoints I suggest we add a new field loadingPositionType that has 3 values: offsets, waypoints_1, waypoints_2. Waypoints are indicated by vehicle flag 26. In theory different cars on a ride could switch between waypoints and offsets but i doubt that is actually done on any ride. This means we can get rid of the type value in the waypoints.
A waypoint would then be defined as:
```
"loadingWaypoints":[
    [ 
       [ [1, 2], [3, 4], [5, 6] ],
       [ [ 7, 8], [9, 10], [11, 12] ] 
    ]
]
```
There will be quite a few waypoints for each car but there will only be one car as the waypoints are only used on flat rides (TBC). The enterprise ride has the most waypoints with numSeats * 4 * 8. 
Its up for debate if the structure should be further split up into the 4 entrance directions and 4/8 track directions. I think it might be best to just keep it as is for that.

**Comment by duncanspumpkin** [comment]
Another thing that is bugging me is that `num_seats` also encodes the bool `is_used_in_pairs`. I think we should split them out into two fields. Then it is much clearer. Unfortunately the loading code will have to recombine them for now as it is still a constraint of the `rct_vehicle` struct but its a start towards sanity.

**Comment by IntelOrca** [comment]
> Another thing that is bugging me is that num_seats also encodes the bool is_used_in_pairs. I think we should split them out into two fields. 

Done, I managed to get it down to 24 occurrences by defaulting seatsInPairs to true and false iff numSeats is <= 1.

**Comment by Gymnasiast** [comment]
This has been addressed now, I think?
