### ISSUE TITLE
Need license for content in this repo

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/objects#137]
I'm working on packaging openrct2 for Debian. This "objects" repo is a dependency for the game, but is missing any licensing information. Looking through what's here, it appears that there's essentially two different types of resources:

- JSON descriptions, which seem to be metadata and largely refer to the original game assets (not shipped with openrct2)
- A subset of the objects also include PNGs, rather than referencing game assets (mostly limited to "official" objects)

Especially for the included artwork, license information is needed. Ideally there would be links to the original source(s) with that information.

Please add some sort of license file to cover the content in this repo, both the JSON files as well as any artwork.

**Comment by Gymnasiast** [comment]
I just added one.
