### ISSUE TITLE
Naming inconsistencies in Footpaths Surfaces & Railings.

### ISSUE THREAD

**Issue by karst** [OpenRCT2/objects#158]
The naming of new paths are inconsistent which looks sloppy.

![image](https://user-images.githubusercontent.com/1516893/143659079-d53c5b25-96f3-4a3b-823a-6551eab7c70e.png)
![image](https://user-images.githubusercontent.com/1516893/143659100-6b9a5c65-3a61-4d8b-850d-47e60e626630.png)

Naming recommendations:
(What you could also do is put Footpath & Queue in front of the names so Paths & Queues are seperated.)

Ash Footpath (Rounded)
Ash Footpath (Square)
Brown Tarmac Footpath (Stairs)
Brown Tarmac Footpath (Sloped)
Brown Tiled Footpath
Circuit Footpath
Circuit Queue
Crazy Paving Footpath (Sloped)
Crazy Paving Footpath (Stairs)
Dirt Footpath (Square)
Dirt Footpath (Rounded)
Green Tarmac Footpath (Stairs)
Green Tarmac Footpath (Sloped)
Green and Brown Tiled Footpath
Grey Tiled Footpath
Invisible Footpath
Mosaic Footpath
Pavement
Pavement Queue
Blue Queue (Stairs)
Blue Queue (Sloped)
Green Queue (Sloped)
Green Queue (Stairs)
Red Queue (Stairs)
Red Queue (Sloped)
Yellow Queue (Stairs)
Yellow Queue (Sloped)
Rainbow Footpath
Rainbow Queue
Red Tarmac Footpath (Stairs)
Red Tarmac Footpath (Sloped)
Red and Brown Tiled Footpath
Road
Rocky Footpath
Tarmac Footpath (Stairs)
Tarmac Footpath (Sloped)
Wooden Footpath

Balustrade
Bamboo Railings (Black)
Bamboo Railings (Brown)
Bamboo Railings (Yellow)
Circuit Board Railings
Concrete Railings
Concrete Railings (Green Supports)
Invisible Railings
Invisible Railings with Circuit Board Queue Banner
Iron Railings
Jungle Railings
Medieval Railings
Rainbow Railings
Space Style Railings (Grey Supports)
Space Style Railings (Red Supports)
Wooden Railings

I'll gladly do this work for you guys if you want me to, just have to tell me and I'll make a zip file for y'all with the edited texts. Just let me know what format you want to use.

**Comment by IntelOrca** [comment]
> (What you could also do is put Footpath & Queue in front of the names so Paths & Queues are seperated.)

I think it would be better to add sub tabs (like the ride tab) for all, path and queue.

> I'll gladly do this work for you guys if you want me to, just have to tell me and I'll make a zip file for y'all with the edited texts. Just let me know what format you want to use.

You do not need to make a zip file. You can fork the repository and edit the files and then make a pull request. But lets first make a decision what the new names should be.

**Comment by ZeeMajoraAlt** [comment]
I feel like RCT2's green tarmac & queue should be renamed to dark green or something like that.
As the shades of green between RCT1 & RCT2's green tarmac are quite different, And the RCT1 & RCT2 green queues are completely different from eachother.
I feel like their current names are just confusing to users as they are not just RCT1/RCT2 counterparts of the same path like many of the other paths.

**Comment by dr-dirt** [comment]
I think these names look much nicer.  I do think it'd be nice to change "Invisible Railings with Circuit Board Queue Banner" to "Invisible Railings (Circuit Board Banner)" to keep specifiers in paranthesis.

**Comment by karst** [comment]
Technically speaking the railing isn't entirely invisible, it has no supports and no railings but it still has a base. So maybe we can find a matching name for that

**Comment by ZeeMajoraAlt** [comment]
Perhaps something involving "Sky Walk"? As that's the original name of the floating circuit board path in time twister.
I think "Sky Walk Platforms" or "Sky Walk Railings" would work well.

**Comment by karst** [comment]
I dont know. I went for Stairs/Sloped and Square/Rounded to keep away the reference of the original games and make it more intuative. But yea we'd need to decide on that.

**Comment by ZeeMajoraAlt** [comment]
Seconding karst here, I feel like naming them after their actual differences is more intuative than just naming them after what game they came from.

**Comment by youngwii2** [comment]
Fair points; not everyone would necessarily be familiar with the differences with path sprites between the games and which style corresponds with which game.

**Comment by karst** [comment]
https://github.com/OpenRCT2/objects/pull/160
