### ISSUE TITLE
Add void terrain edge type as official object

### ISSUE THREAD

**Issue by Xtreme97-RCT** [OpenRCT2/objects#163]
Refer to https://github.com/OpenRCT2/OpenRCT2/discussions/16271 for context.

Not sure what the procedure is for adding new official objects so I'll upload the file here and start it as an issue.

[x97_void_terrain_edge.zip](https://github.com/OpenRCT2/objects/files/7748085/x97_void_terrain_edge.zip)

**Comment by Gymnasiast** [comment]
How, would you say, will people use this?

(Asking because bundling an object with the game requires a good use case.)

**Comment by Xtreme97-RCT** [comment]
It would likely be used similarly to the current void terrain surface object, to create black/void space around map content without showing the map edge. The discussion I linked shows an example, and another example can be found in the park Gladsheim on New Element: https://www.nedesigns.com/park/5338/gladsheim/, wherein the creators used custom objects to blank out the intended map edge.

**Comment by Gymnasiast** [comment]
Right, so there is a use case. Good.

The normal procedure to add official object is to fork the repository (if you haven’t already), add the object and then create a pull request.

**Comment by Xtreme97-RCT** [comment]
Can do. Do you want me to change SourceGame to official in the object.json file? And should I change the file name at all or leave it alone?

**Comment by Gymnasiast** [comment]
The filename and ID should be `official.terrain_edge.void`.  The source game should indeed be changed to "official". Otherwise it looks good to go.

**Comment by Gymnasiast** [comment]
This was added in https://github.com/OpenRCT2/objects/pull/164.
