### ISSUE TITLE
Reversed version of vanilla vehicles

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/objects#176]
RCT1 includes reversed looping and reversed 4-seater wooden coaster cars, which are not available in RCT2. This project would be creating new .json objects which use the RCT2 sprites to create official reversed versions of select trains.

@frutimax points out that some parks run their B&M inverted coasters in reverse for special occasions, this could be included in this project.

A reversed version of the corkscrew coaster would not go too remiss, as Arrow's shuttle coaster runs half the train backwards.

Thoughts?

**Comment by Gymnasiast** [comment]
I think including a reversed vehicle for the 4-seater wooden RC cars and Looping RC make sense for RCT1 parity. The rest is optional, I’d say.

**Comment by SpartanFrederic104** [comment]
Would these reversed trains have ride rating boosts like the reversed six-seater wooden coaster trains or not?

**Comment by Gymnasiast** [comment]
That would make sense, I think. After all, that is the reason why one would reverse a train in real-life.

**Comment by 733737** [comment]
If the stated goal of OpenRCT2 is to expand the game, and there have been multiple newly added coaster types with pools upcoming, why can't we add reversed corkscrew trains or twister trains? surely it's not a tall ask, they aren't unrealistic, and wouldn't bloat compile time or object data size as they are sprite offsets

**Comment by ZeeMaji** [comment]
As of https://github.com/OpenRCT2/OpenRCT2/pull/19305 you can now reverse _any_ train/vehicle without even needing a separate object for a reversed version, this issue can probably be closed now as the reverse option supersedes having separate reversed objects.
