### ISSUE TITLE
rckc ride type order makes it unavailable for mini coaster

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/objects#180]
https://github.com/OpenRCT2/objects/blob/b07258c5ecd1ba2adc0b5b7bae0eb2f9b5fa2f11/objects/rct2/ride/rct2.ride.rckc/object.json#L9

Flipping the order will make it available for mini coaster again, I think.

**Comment by Gymnasiast** [comment]
The order was originally flipped, but that caused problems as well, though I cannot remember which ones exactly.

Can you provide an affected save so I can check?

**Comment by spacek531** [comment]
Clarification, it was not showing up in the object selection, it did show up in the mini coaster vehicle selection dropdown but only if the classic mini coaster version was selected.

**Comment by Gymnasiast** [comment]
Vehicles always show up once in the object selection. It’s just that this one is special and has two ride types it can work with.

**Comment by Gymnasiast** [comment]
When the appropriate bits are in, I am simply going to use the RCT1 variant of the Rocket Cars and make the RCT2-originated ones just for the (Schwarkopf) Mini RC again. That will also solve this problem.

**Comment by Gymnasiast** [comment]
This has now been carried out:
- https://github.com/OpenRCT2/objects/commit/376e97f556b6d7b5b396faf3062741bda320e398
- https://github.com/OpenRCT2/objects/commit/f9d43b676cb056fd82a6ffdcc83288615201a99c
