### ISSUE TITLE
Wildflowers terrain

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/objects#181]
I have, after a lot of painstaking work, imported the beta RCT1 grass texture from development screenshots and ride thumbnails into an OpenRCT2 terrain_surface object. As an object that was part of the RCT1 series officially, although never released, I think it should be added to the OpenRCT2 official objects like the other DLC objects.

**Comment by ZeeMajora** [comment]
With this terrain surface now being featured in two ride thumbnails in this repo (with more coming in the future) i see that as even more of a reason to officially implement it.

**Comment by Gymnasiast** [comment]
This is the kind of object I would put into add-on pack: official, but not part of the regular download. That would require some work, though.

**Comment by Gymnasiast** [comment]
Since add-on packs (and the store) are taking longer than I had hoped, I think it’s fine to have them in the game proper. Can one of you create a pull request?
