### ISSUE TITLE
Missing RCT1 fences

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/objects#182]
There are 4 fences from RCT1 that are not in RCT2, Being three versions of the brown wooden fence and an odd height abstract fence. I believe these all should be implemented for better RCT1 accuracy.
![DeepinScreenshot_select-area_20220426203647](https://user-images.githubusercontent.com/42477864/165415362-93116362-04f5-42de-8ff8-8bbb092cbab2.png)
![DeepinScreenshot_select-area_20220426203720](https://user-images.githubusercontent.com/42477864/165415617-51c95306-7584-4614-a4ea-b98a62b3e0f7.png)
The closest RCT2 counterparts to the brown wooden fences are not the right color as they are much darker and the abstract fence is a different height to it's closest rct2 counterpart, left are the RCT1 fences and right are the RCT2 fences.
![DeepinScreenshot_select-area_20220426204047](https://user-images.githubusercontent.com/42477864/165415604-52a0ab21-e760-4827-a2d1-a33cc1fb7158.png)
![DeepinScreenshot_select-area_20220426204242](https://user-images.githubusercontent.com/42477864/165415720-63c6f5e8-4b79-4e03-953e-6bd623367b5b.png)
I have additionally already ported all of them to json objects as seen above and made the abstract fence fully recolorable to make it more in line with the rest of the rct2 abstract fences so the objects are ready should we decide they should be implemented.

**Comment by ZeeMajora** [comment]
To add to this, the white fence also looks a bit different from it's RCT2 counterpart upon closer inspection
Left = RCT2 Right = RCT1
![Screenshot_select-area_20220810162321](https://user-images.githubusercontent.com/42477864/184012956-a66d6b5e-1adb-40d1-be5e-e2bedaafb00a.png)
For all of these alongside the already existing red wooden fence it'd likely be wise to mark them as compatibility objects once that flag is implemented should these fences be added officially.

**Comment by Gymnasiast** [comment]
It seems a bit overkill to me, but if enough people really want it, I will consider it.

**Comment by ZeeMajora** [comment]
I don't really think it'd hurt to include them once the compatibility object flag is added, we already include the red wooden fence and asides from the odd height glass wall none of them require new images so their file size impact on the repo at large would be very minimal.

**Comment by ZeeMajora** [comment]
To further add to this the jungle theming wooden post walls also have different heights similarly to the glass wall, with the rct1 versions of the fences being shorter than their rct2 counterparts.
![Screenshot_select-area_20230223020650](https://user-images.githubusercontent.com/42477864/220840569-2089a37b-fdf4-4261-8d9e-bb60fba0bbcd.png)
Noticed this whilst doing the rafts thumbnail for the rct1 vehicles project.

**Comment by Gymnasiast** [comment]
I assume you already have some draft objects for these? Can you upload them so I can check them out?

**Comment by ZeeMaji** [comment]
All of the walls have been implemented by #275
