### ISSUE TITLE
American style steam trains with open cars

### ISSUE THREAD

**Issue by ZeeMajora** [OpenRCT2/objects#189]
We could create an open cars version of the american style steam trains by using sprites from AML1.DAT and NRL.DAT, i think this would make for a nice addition to the game to make the american steam trains more consistent with the standard steam trains.
![DeepinScreenshot_select-area_20220531225911](https://user-images.githubusercontent.com/42477864/171319028-316c0bc9-9c7d-49aa-9982-eef86daadbec.png)

**Comment by Gymnasiast** [comment]
Personally, I think it would be better as a custom object, but I mentioned this in the Discord chat to see what others think.
