### ISSUE TITLE
Cannot load full Catalan translation from Localisation repository

### ISSUE THREAD

**Issue by J0anJosep** [OpenRCT2/objects#191]
I am trying to load the Catalan localisation with:

`python3 language_load.py -l ca-ES -i ../Localisation/objects/ca-ES.json -v`

in my local copies of "objects" and "Localisation" repositories.

This is the [result](https://github.com/J0anJosep/objects/commit/c0393839fa9e8369f9bab6de575b1efa58fe67e1)

As you can check, only the objects with ids \*.station.\* find the correct translation. Other objects have different ids in the *.json files in "Localisation" and "objects" repositories.

As an example, "'Goliath' Sign" has these ids:
In Localisation: "rct2.glthent"
In objects: "rct2.scenery_large.glthent"

As they have different ids, language_load.py fails to load the translation. I expected all strings would have been loaded. I don't know whether I am missing something here and should run some other script first.

**Comment by Gymnasiast** [comment]
This is expected as the object IDs have been updated. It’s our responsibility to sync the translations anyway, so don’t worry about it.

**Comment by J0anJosep** [comment]
Thank you!

I didn't know about it.
