### ISSUE TITLE
Scenery group ordering

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/objects#244]
Now that we can have 255 scenery groups visible in the window, it's common for sandbox play to just pick all the groups. But, annoyingly, the expansion groups show up in the middle of the list instead of the end.

![image](https://github.com/OpenRCT2/objects/assets/5436387/6cdf1d92-fb86-4993-9fc2-892aba8c1ec0)

This ordering is set by the `priority` field of each groups' json file ([example](https://github.com/OpenRCT2/objects/blob/e71cbcbe8ccb87735189abf3255edc75f3a52fbf/objects/rct2/scenery_group/rct2.scenery_group.scgsport.json#L26)). RCT2 groups use priorities 20-39, but for both Wacky Worlds and Time Twister, all groups have priority 25 (the same as Jurassic theming) for some reason (probably Frontier laziness again? who can say). Not only are they in the middle of the group list, but since they all have the same priority, their effective order is inconsistent each time the game is loaded, meaning the player cannot rely on muscle memory to find a particular group.

It would be nice to change the expansion groups' json data to give them priorities above 39, in order to have the groups sorted by game. This is a trivial data change, but I wanted to see if anyone had strong opinions about it.

**Comment by Gymnasiast** [comment]
The only downside I can think about is that most or all custom groups have it set to 40 too. So those WW/TT groups would then mix with custom group.

But on the whole, I think having WW/TT groups sort between custom groups is preferable to sorting it between base game groups.

**Comment by fidwell** [comment]
That's a good point. I wonder how many people actually use both expansion groups and custom groups at once, though? Probably not many. Definitely not as many as would use all the non-custom groups, I'd bet.
