### ISSUE TITLE
RCT1 Toilets should use graphics from CSG

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/objects#253]
Currently the RCT1 toilets object uses graphics supplied from here, these should probably be removed as that's inconsistent with the rest of the RCT1 objects which read their graphics from CSG and have a noCsgImages table for fallback images. And it seems rather dubious to supply unmodified RCT1 sprites in an official object.

**Comment by Gymnasiast** [comment]
This object predates the compatibility flags and even the noCsgImages.

I’m not sure I would be happy changing it, though - unlike many other cases, the artwork is nicer than RCT2’s IMO.

**Comment by ZeeMaji** [comment]
I didn't mention compat flags, i don't believe any of the current RCT1 objects in this repo should be marked as compat/superseded objects asides from maybe the red fence as they're all entirely unique or for rct1 ride types.

The only change i'm suggesting is making the RCT1 toilets use images from CSG and giving them a noCsgImages table like the rest of the RCT1 objects along with removing the unmodified original game sprites from the object's images folder. The artwork would remain the same for those who have RCT1 (the people who probably would be using the RCT1 toilets) and just show RCT2's toilets sprites as fallback images for those who don't have RCT1.

**Comment by Gymnasiast** [comment]
The disadvantage of that is that they will appear the same for people without RCT2, which is confusing. I honestly don’t think that having just four tiny images in our repo is a problem.

**Comment by ZeeMaji** [comment]
Couldn't you say the same for other RCT1 objects we have that use noCsgImages right now like the vehicles and path surfaces? I'd say those are a lot more confusing than this would be. Besides we do have a system that warns the user if they use rct1 objects while not having rct1 linked to let them know that rct1 objects will use fallback images so i feel like that will reduce a lot of the confusion should there be any.

As for making the experience for people without RCT1 worse, that's technically true but to be fair are people without RCT1 really going to be the types to use the RCT1 toilets in the first place? It feels like a really niche thing to be worried about as most people who are going to use the RCT1 toilets are probably the type to have RCT1 linked.

It may only be a few tiny images but to me it still just feels rather dubious to pack unmodified RCT1 images with an officially included object.
