### ISSUE TITLE
Sputnik cars for mini suspended coaster uses vanilla vehicle sprites for diagonals inclines.

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/objects#264]
The sputnik cars from WW literally just use the vanilla batflyer sprites on the diagonal inclines, i could not even make this up even if i tried.

What the hell frontier.

![Screenshot_select-area_20240115121427](https://github.com/OpenRCT2/objects/assets/42477864/31a0cbe2-3310-45f7-b270-8a8f8b02bb8f)

**Comment by 733737** [comment]
should be made a priority for opengraphics

**Comment by Gymnasiast** [comment]
If I’m not mistaken, you could try and remove that sprite group altogether, making it fall back on the 25 degree sprites. It will look _slightly_ off, but a whole lot less than switching images halfway through.

**Comment by ZeeMaji** [comment]
I was thinking of doing that, it'll look kind of crappy but it'd be better than... this. So that's probably our best bet in regards to the original graphics.

**Comment by ZeeMaji** [comment]
Removing the sprite group alltogether won't work, as it'll just fall back to the flat sprites.

However i can just change the images table to reference the 25 degree sprites, that should do the trick.
