### ISSUE TITLE
large tower section pieces in WW's kremlin/drab scenery pieces from the Europe Theming set do not allow walls to be placed on all four sides

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/objects#296]
When attempting to build walls around these objects, exactly one side of the object will not allow for wall placement. This becomes especially frustrating when trying to properly renovate From The Ashes.
![image](https://github.com/OpenRCT2/objects/assets/108596959/b460d5b1-e2a6-4b62-bff6-ca165878c59d)

**Comment by Gymnasiast** [comment]
So, if I’m not mistaken, that’s:
- [ ] Nice base
- [ ] Drab base 1
- [ ] Drab base 2
- [ ] Nice mid-section
- [ ] Drab mid-section
- [ ] Nice top section
- [ ] Drab top section

?

**Comment by HtotheTML** [comment]
Yes.
