### ISSUE TITLE
WWTT Flying saucers vehicles should be renamed

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/objects#309]
Now that the flying saucers ride type groups vehicles, it would probably make sense to rename the WWTT flying saucers vehicles as they are refered to as separate Rides (eg: Flower Power Ride) when they are just vehicles now.

The skidoo dodgems already refer to themselves as dodgems. So perhaps it would make sense to rename the others in the same way?

Flower Power Dodgems
Chinese Dragonhead Dodgems
Cyclops Dodgems

This only affects the flying saucers vehicles btw, the TT dodgems vehicles are already called dodgems (eg: Fighting Knights Dodgems) so they are fine.

**Comment by Gymnasiast** [comment]
Seems like a good idea to me.
