### ISSUE TITLE
Incorrect wall boundaries on large WW/TT scenery objects

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/objects#323]
On nearly every single 1x2, 1x4, 2x2, 3x3, and 4x4 sized scenery object in WW and TT, the spots where walls can be placed along the tiles those objects occupy are consistently incorrect.
Pictured below are all of the scenery items with incorrect collision shown with walls (I've attached a save file of this in case you want a closer look)
[Experimentation.zip](https://github.com/OpenRCT2/objects/files/14784806/Experimentation.zip)

Africa, Antarctic, Asia, Australasia
![Africa, Asia, Australasia](https://github.com/OpenRCT2/objects/assets/108596959/84343a06-f965-4cc1-9aa6-bd6846cb2a2c)

Europe, North America, South America, Roaring Twenties
![Europe, NA, SA, 20s](https://github.com/OpenRCT2/objects/assets/108596959/64c96cfc-e3a2-4a33-93b0-c064b948304f)

Rock 'n' Roll, Future, Prehistoric, Dark Ages
![RocknRoll, Future, Prehistoric, Dark Ages](https://github.com/OpenRCT2/objects/assets/108596959/984c2217-b308-4d1f-acdf-256614cc8d3a)

Mythological
![Mythological](https://github.com/OpenRCT2/objects/assets/108596959/29bbaea2-e929-4726-8142-4897b8473173)

The only large scenery objects that had proper wall boundaries were these items:
![exceptions](https://github.com/OpenRCT2/objects/assets/108596959/ddabe991-3ce5-465a-acca-2288bd762081)

Going off of the default rotation for scenery items when the window is opened, the incorrect boundaries for each sized object looks like this:
![guide](https://github.com/OpenRCT2/objects/assets/108596959/4527b4fb-0542-4d81-a367-041ae03bb4c0)
The tiles and walls are color-coded to make it easier to discern which tiles have usable wall spots. If the red/green gate is used, a wall can be placed on either side of that edge.

**Comment by HtotheTML** [comment]
The full list of items with these issues are as follows:

Wacky Worlds

Africa Theming
- [ ] 3x3 Jungle Tree 1
- [ ] 2x2 Jungle Tree 2
- [ ] 3x3 Jungle Tree with Vines
- [ ] 3x3 Jungle Tree with Leopards

Antarctic Theming
- [ ] 3x3 Satellite Dish
- [ ] 2x2 Big Geosphere
- [ ] 4x4 Radar Dish
- [ ] 3x3 Helipad
- [ ] 4x4 Ice Formation
- [ ] 4x4 Ice Formation

Asia Theming
- [ ] 2x2 Bamboo Roof Corner
- [ ] 1x2 Bamboo Roof
- [ ] 2x2 Bamboo Roof Inverted Corner
- [ ] 4x4 Chinese Dragon
- [ ] 3x3 Evil Samurai
- [ ] 2x2 Fat Buddha
- [ ] 3x3 Geisha
- [ ] 2x2 Golden Buddha
- [ ] 3x3 Good Samurai
- [ ] 3x3 Great Wall Of China Turret Straight
- [ ] 3x3 Great Wall Of China Turret Corner
- [ ] 2x2 Maharaja Palace Tower Base
- [ ] 2x2 Maharaja Palace Tower Column
- [ ] 2x2 Maharaja Palace Tower Top
- [ ] 4x4 Maharaja Palace Dome
- [ ] 2x2 Adult Indian Elephant
- [ ] 2x2 Shiva
- [ ] 3x3 Pagoda
- [ ] 3x3 Pagoda
- [ ] 3x3 Pagoda
- [ ] 3x3 Pagoda Tower

Australasian Theming
- [ ] 1x2 Aboriginal Plain Tile
- [ ] 1x2 Aboriginal Snake Artwork
- [ ] 1x2 Aboriginal Spirit Artwork
- [ ] 3x3 HMS Endeavour
- [ ] 3x3 Eucalyptus Tree

Europe Theming
- [ ] 3x3 Big Ben and the Houses of Parliament
- [ ] 4x4 Atomium
- [ ] 3x3 Windmill
- [ ] 2x2 Eiffel Tower
- [ ] 2x2 Circus
- [ ] 2x2 1950s Rocket
- [ ] 2x2 Sputnik
- [ ] 1x2 Tudor Roof Piece 3
- [ ] 1x2 Tudor Roof Piece 4
- [ ] 3x3 Old Overgrown Tree

North America Theming
- [ ] 1x2 Log Cabin Side Chimney
- [ ] 3x3 Skyscraper Roof Piece
- [ ] 3x3 Skyscraper Tip
- [ ] 2x2 Cowboy 1
- [ ] 2x2 Cowboy 2
- [ ] 2x2 Native American
- [ ] 2x2 Statue of Liberty
- [ ] 2x2 Washington Statue
- [ ] 2x2 Redwood Tree
- [ ] 3x3 Space Orbs
- [ ] 1x4 Suspension Bridge Start side 1
- [ ] 1x4 Suspension Bridge Start side 2
- [ ] 1x4 Suspension Bridge Tower side 1
- [ ] 1x4 Suspension Bridge Tower side 2
- [ ] 1x4 Suspension Bridge Cable Section

South America Theming
- [ ] 1x2 Temple Wall Piece with Head
- [ ] 1x2 Temple Broken Wall Piece with Head
- [ ] 2x2 Easter Island Statue
- [ ] 2x2 Gold Llama
- [ ] 3x3 Mangrove Tree
- [ ] 2x2 Large Rainforest Tree
- [ ] 2x2 Gold Statue 1
- [ ] 2x2 Gold Statue 2

Time Twister

Roaring Twenties Theming
- [ ] 4x4 Period Diner
- [ ] 1x2 Period Sailing Yacht
- [ ] 4x4 Luxury Liner Bow
- [ ] 4x4 Luxury Liner Mid Section
- [ ] 4x4 Luxury Liner Stern
- [ ] 4x4 Seaplane Pits
- [ ] 4x4 Seaplane Pits
- [ ] 4x4 Marquee
- [ ] 2x2 Harbour Wall Corner Piece
- [ ] 2x2 Harbour Wall Corner Piece
- [ ] 2x2 Harbour Wall with Dock
- [ ] 2x2 Harbour Dock

Roaring Twenties Wall Sets
- [ ] 1x2 New York Wall Piece
- [ ] 1x2 New York Wall Piece
- [ ] 1x2 New York Wall Piece
- [ ] 2x2 New York Entrance
- [ ] 3x3 New York Wall Piece
- [ ] 3x3 New York Wall Piece
- [ ] 3x3 New York Wall Piece
- [ ] 3x3 New York Wall Piece
- [ ] 2x2 New York Roof Piece
- [ ] 2x2 New York Inverted Corner Roof
- [ ] 2x2 New York Roof Piece
- [ ] 1x2 New York Roof Piece
- [ ] 2x2 Art Deco Corner with Windows
- [ ] 2x2 Art Deco Corner with Railings
- [ ] 2x2 Art Deco Top Corner Section
- [ ] 1x2 Prison Door
- [ ] 2x2 Prison Water Tower

Rock 'n' Roll Theming
- [ ] 3x3 Jet Aeroplane
- [ ] 3x3 Jet Aeroplane
- [ ] 3x3 Jet Aeroplane
- [ ] 3x3 Rock Band Tour Bus
- [ ] 3x3 Giant Drum Kit

Future Theming
- [ ] 4x4 Alien Historical Structures
- [ ] 2x2 Alien Historical Structures
- [ ] 4x4 UFO Crash Site
- [ ] 2x2 Sandstone Skyscraper Bottom Inverted Corner
- [ ] 2x2 Sandstone Skyscraper Bottom Inverted Corner
- [ ] 2x2 Sandstone Skyscraper Bottom Inverted Corner
- [ ] 2x2 Sandstone Skyscraper Bottom Inverted Corner
- [ ] 2x2 Sandstone Skyscraper Bottom Inverted Corner
- [ ] 3x3 Sandstone Walkway T-Junction
- [ ] 3x3 Sandstone Walkway Corner
- [ ] 3x3 Sandstone Walkway Cross Section
- [ ] 3x3 Sandstone Walkway End Section
- [ ] 2x2 Small Red Meteor Crater
- [ ] 4x4 Large Red Meteor Crater
- [ ] 1x2 Red Meteor Crater Corner
- [ ] 1x2 Red Meteor Crater Corner
- [ ] 2x2 Alien Structure Large
- [ ] 3x3 Alien Structure Large
- [ ] 3x3 Alien Structure Large
- [ ] 4x4 Alien Skylight Large

Prehistoric Theming
- [ ] 4x4 Giant Mangrove Tree
- [ ] 4x4 Stone Age Temple
- [ ] 4x4 Volcano with small trees
- [ ] 2x2 Giant Dinosaur Footprint
- [ ] 4x4 Bubbling Tarpit
- [ ] 1x2 Meteor Crater Corner
- [ ] 1x2 Meteor Crater Corner
- [ ] 2x2 Small Meteor Crater
- [ ] 4x4 Large Meteor Crater
- [ ] 1x2 Cave Entrance

Dark Age Theming
- [ ] 4x4 Dark Ages Tavern
- [ ] 1x2 Dark Age Village Roof Piece
- [ ] 2x2 Dark Age Village Corner Roof Piece
- [ ] 2x2 Dark Age Village Inverted Roof Piece
- [ ] 2x2 Castle Inverted Corner
- [ ] 2x2 Castle Portcullis
- [ ] 1x2 Castle Entrance
- [ ] 3x3 Castle Tower Corner Piece
- [ ] 3x3 Castle Tower Corner Piece
- [ ] 3x3 Castle Tower Cross Piece
- [ ] 3x3 Castle Tower Straight Piece
- [ ] 3x3 Castle Tower T Piece
- [ ] 3x3 Castle Tower T Piece
- [ ] 2x2 Feast Table
- [ ] 2x2 Robin Hood's Hut
- [ ] 2x2 Robin Hood's Hut
- [ ] 4x4 Robin Hood's Camp
- [ ] 2x2 Peasant Hut
- [ ] 2x2 Plough
- [ ] 3x3 Large Oak
- [ ] 2x2 Large Elm Tree

Mythological Theming
- [ ] 2x2 Roman Palace Corner Piece
- [ ] 1x2 Roman Palace End Piece
- [ ] 2x2 Roman Palace Straight Piece
- [ ] 2x2 Roman Palace Cross Section
- [ ] 2x2 Roman Palace Corner Piece
- [ ] 2x2 Roman Palace Cross Section
- [ ] 2x2 Roman Palace Straight Piece
- [ ] 2x2 Roman Palace Corner Piece
- [ ] 1x2 Roman Palace End Piece
- [ ] 2x2 Roman Palace Straight Piece
- [ ] 2x2 Roman Palace Cross Section
- [ ] 2x2 Roman Palace Corner Piece
- [ ] 2x2 Roman Palace Cross Section
- [ ] 2x2 Roman Palace Straight Piece
- [ ] 2x2 Cyclops Statue
- [ ] 2x2 Forbidden Fruit Tree
- [ ] 4x4 Ash Tree with Nymphs
- [ ] 2x2 Hades Statue

**Comment by ZeeMaji** [comment]
This should now be fixed as of #333
