### ISSUE TITLE
Base Block doesn't refund $15 when deleted

### ISSUE THREAD

**Issue by astraylife1** [OpenRCT2/objects#345]
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.13 (fe628af on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Base block toontowner.scenery_small.xxbbbr01_fix.parkobj does not refund $15 when deleting like the other base blocks.

### Steps to reproduce

Build base block at $20 cost
Delete
No refund

### Attachments

![Base Block](https://github.com/user-attachments/assets/054b06de-eeca-4129-a5d2-f9da5d03fe17)

**Comment by Gymnasiast** [comment]
I moved your issue to the `object` repository. It should be easy to fix as it’s just JSON files, maybe you want to try your hand?

**Comment by astraylife1** [comment]
I can try my best. Do I need to start a PR?

**Comment by tupaschoal** [comment]
> I can try my best. Do I need to start a PR?

Yeah, when you think you've got it, you make a PR on this repository which we can review and merge.
Then at another point we'll merge the objects into the main repo and it will fixe the issue in the game

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/objects/commit/763b4795b9d6b4a46d44d916d1d881170286e581.
