### ISSUE TITLE
Door Sounds are incorrect

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/objects#47]
https://github.com/OpenRCT2/objects/blob/master/tools/objexport/PropertyExtractor.fs#L655
Above line should have been a right shift.

All door sounds need to be looked at and reset back to their correct value. Could possibly just do a re-export as I'm not sure if there are many doors.

**Comment by Gymnasiast** [comment]
Code has been fixed here: https://github.com/OpenRCT2/objects/commit/3372b9b6437109b5645e3fcead35eb5d55270c6e

Objects have been fixed here: https://github.com/OpenRCT2/objects/commit/45400c784bc1fd54619077220557cdeec1351ef0
