### ISSUE TITLE
Hoverboard cars (Time Twister) have wrong sprite when traveling diagonally

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/objects#58]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 617372f

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

The hoverboard cars from Time Twister use the wrong sprites while traveling diagonally up the chainlift, and at the start of a diagonal drop. You will suddenly see them move sideways, and at an angle.
Also happens in vanilla RCT2 (with Time Twister). 

![image](https://user-images.githubusercontent.com/6469413/40589307-5d6766c0-61eb-11e8-9cb9-dc961d89eca4.png)

[Gemini City.zip](https://github.com/OpenRCT2/OpenRCT2/files/2042886/Gemini.City.zip)

**Comment by Fred-1044276** [comment]
This also affects the Sputnik and Dragonfly cars.
