### ISSUE TITLE
Certain Water Coaster vehicles claim incorrect number of passengers per vehicle

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/objects#62]
**OS:** Windows 8
**Version:** 0.2.5
**Commit/Build:** d64b73c

On the Water Coaster, both the Flying Boats vehicles and the Trilobite vehicles falsely claim to seat 16 passengers per boat, when like all the other vehicles for the Water Coaster, they actually seat 6. 

Default Coaster Boat vehicles and Manta Ray vehicles both display the correct number.

These two vehicle types also have a much more verbose description, which is probably related.

(First reported on [this thread on reddit](https://www.reddit.com/r/openrct2/comments/fq66ba/the_flying_boats_on_the_water_coaster_claim_to/))

Not sure if this is a vanilla bug or not. My vanilla install is broken.

- [ ? ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a Water Coaster
2. Set it to have the Flying Boats or Trilobite Boats vehicle and observe how many passengers per boat it claims to seat

**Screenshots / Video:**

![Forest Frontiers 2020-03-27 22-13-11](https://user-images.githubusercontent.com/26573303/77815544-2b6ae180-7079-11ea-98f0-570555c5f5d2.png)
![Forest Frontiers 2020-03-27 22-13-44](https://user-images.githubusercontent.com/26573303/77815546-2c9c0e80-7079-11ea-86c4-5a895e64c86e.png)
![Forest Frontiers 2020-03-27 22-13-56](https://user-images.githubusercontent.com/26573303/77815547-2d34a500-7079-11ea-8e70-282536363ace.png)
![Forest Frontiers 2020-03-27 22-13-59](https://user-images.githubusercontent.com/26573303/77815548-2d34a500-7079-11ea-9b7d-43c3da086509.png)

**Comment by Gymnasiast** [comment]
@ocalhoun6 You can solve this yourself, if you like. Find the appropriate JSON files and modify the capacity strings.

**Comment by tupaschoal** [comment]
It kind of is an "original bug", but in the sense that the capacity has a typo, because the vehicles themselves would never fit 16 (just do some visual calculations hehehe)

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/objects/blob/master/objects/rct2tt/ride/rct2.tt.trilobte.json#L102-L114

Interestingly dutch state the correct capacity.

**Comment by Gymnasiast** [comment]
Hm, that's odd. I must have changed that, but I'm not sure why I didn't change it for the other languages.
