### ISSUE TITLE
Optionally only dump untranslated objects with language_load.py

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/objects#98]
To make it even easier to find the last remaining objects that require translation, we should add an option to `language_load.py` that allows for only dumping untranslated objects.

**Comment by tupaschoal** [comment]
I was thinking about that. I'm also thinking if it should output fill the missing translation with the fallback language, now that we provide the reference string, because then you can also look for blanks only.

**Comment by AaronVanGeffen** [comment]
Hmm, I was happy to have the reference string filled out instead of a blank, to be honest! It allows for very quick text selection — especially if part of the English string can be re-used (proper nouns like "New York" come to mind).
